# Generated by Django 5.0.1 on 2024-02-28 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=255, unique=True)),
                ('order_date', models.DateField()),
                ('customer_name', models.CharField(max_length=255)),
                ('party_po_no', models.CharField(blank=True, max_length=255, null=True)),
                ('party_po_date', models.DateField(blank=True, null=True)),
                ('company_short_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=255)),
                ('material_uom', models.CharField(max_length=255)),
                ('po_qty', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saleorderapi.order')),
            ],
        ),
    ]
