# Generated by Django 5.0 on 2024-02-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0002_customuser_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone_number', models.CharField(max_length=15)),
                ('current_destination', models.CharField(max_length=15)),
                ('data_json', models.JSONField()),
            ],
        ),
    ]
