# Generated by Django 5.0 on 2024-02-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0003_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='current_destination',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='data_json',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver_phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
