# Generated by Django 5.0 on 2024-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0006_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='on_path',
            field=models.BooleanField(default=False),
        ),
    ]
