# Generated by Django 5.0.2 on 2024-02-28 06:25

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0007_vehicle_on_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalVehicle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('vehicle_number', models.CharField(db_index=True, max_length=20)),
                ('on_path', models.BooleanField(default=False)),
                ('driver_name', models.CharField(max_length=100)),
                ('status', models.CharField(blank=True, null=True)),
                ('driver_phone_number', models.CharField(max_length=15, null=True)),
                ('current_destination', models.CharField(max_length=150, null=True)),
                ('last_location', models.CharField(max_length=150, null=True)),
                ('data_json', models.JSONField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical vehicle',
                'verbose_name_plural': 'historical vehicles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
