# Generated by Django 5.0.2 on 2024-02-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0008_historicalvehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='cuurent_carrying',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='past_carried',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cuurent_carrying',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='past_carried',
            field=models.JSONField(null=True),
        ),
    ]
