# Generated by Django 5.0.2 on 2024-02-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0010_historicalcustomuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='ongoing_status',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ongoing_status',
            field=models.JSONField(null=True),
        ),
    ]
