# Generated by Django 5.0.2 on 2024-02-29 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0011_historicalvehicle_ongoing_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalvehicle',
            old_name='cuurent_carrying',
            new_name='current_carrying',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='cuurent_carrying',
            new_name='current_carrying',
        ),
    ]
