# Generated by Django 5.0 on 2024-03-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0012_rename_cuurent_carrying_historicalvehicle_current_carrying_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='driver_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvehicle',
            name='on_path',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='on_path',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
