# Generated by Django 5.0 on 2024-03-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0013_alter_historicalvehicle_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvehicle',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='current_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='fuel_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='last_acc_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='last_status_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='last_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='tag_ids',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='total_odometer',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='vehicle_make',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='vehicle_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='vehicle_type_value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historicalvehicle',
            name='vehicle_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_acc_on',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_status_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tag_ids',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_odometer',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_make',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type_value',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_year',
            field=models.IntegerField(null=True),
        ),
    ]
