# Generated by Django 5.0 on 2024-03-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0014_historicalvehicle_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvehicle',
            name='ongoing_status',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='ongoing_status',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
