"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import  os
from django.contrib.messages import constants as messages
import socket
from django.conf import settings
from logging.handlers import RotatingFileHandler


BASE_DIR = Path(__file__).resolve().parent.parent

GOOGLE_API_KEY = "AIzaSyASi4cb1m9qFTqyAk95rr1Nzi_cyAaFQY4"
API_CALLS = True
API_CALLS_TIME = 30
ALLOW_AI = False





MESSAGE_TAGS = {
        messages.DEBUG: 'alert-secondary',
        messages.INFO: 'alert-info',
        messages.SUCCESS: 'alert-success',
        messages.WARNING: 'alert-warning',
        messages.ERROR: 'alert-danger',
 }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#$xm@-#_a^te52k33y&no4fh5&qezyj#fey&pml@5czvb10gnk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

local_ip = socket.gethostbyname(socket.gethostname())

ALLOWED_HOSTS = ['localhost', '127.0.0.1','10.10.4.94','192.168.1.7','10.30.1.110','example.com','10.10.1.18','192.168.31.232','192.168.240.63','192.168.1.5','10.10.4.151','192.168.1.3','115.244.173.10']
print(f'Allowed Hosts : {ALLOWED_HOSTS}')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework','api',
    'managment',
    'inlet',
    'outlet',
    'units',
    'simple_history'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',    
    'django.middleware.gzip.GZipMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # user Added Middelware
    'main.middleware.AuthenticationMiddleware',  #Custom Auth
    # 'main.middleware.SessionTimeoutMiddleware', #Session Expiray
    
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# qrwrwr
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'tool_tracking',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',  
        'PORT': '5432',           
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    'static'
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



AUTH_USER_MODEL = 'managment.CustomUser'


# Auto Logout (In SEC)
SESSION_COOKIE_AGE = 3600  # 30 minutes (30 * 60 seconds)


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'




LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'api_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(settings.MEDIA_ROOT, 'api_logs.log'),
            'formatter': 'verbose',
            'maxBytes': 1024 * 1024 * 10, 
            'backupCount': 5, 
        },
        'utility_api_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(settings.MEDIA_ROOT, 'utility_api_logs.log'),
            'formatter': 'verbose',
            'maxBytes': 1024 * 1024 * 10, 
            'backupCount': 5, 
        },
    },
    'loggers': {
        'api': {
            'handlers': ['api_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'utility_api': {
            'handlers': ['utility_api_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}