# Generated by Django 5.0 on 2023-12-14 20:35

import django.utils.timezone
import shortuuid.main
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('batch_id', models.CharField(editable=False, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('in_progress', 'In Progress'), ('dead', 'Dead')], default='in_progress', max_length=20)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_json', models.JSONField(default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('product_id', models.CharField(primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_gstin', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductIndex',
            fields=[
                ('gate_inward_No', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'verified'), ('active', 'Active'), ('deactive', 'Deactive'), ('in_progress', 'In Progress'), ('dead', 'Dead')], default='unverified', max_length=20)),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('arrive_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('party_challan_no', models.PositiveIntegerField()),
                ('part_bill_no', models.PositiveIntegerField(serialize=False)),
                ('part_date', models.DateField()),
                ('UOM', models.CharField(max_length=10)),
                ('po_no', models.CharField(max_length=20)),
                ('rate', models.PositiveIntegerField()),
                ('ammount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductIndexItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_uuid', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True)),
                ('quantity_requested', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField()),
            ],
        ),
    ]
