# Generated by Django 5.0 on 2023-12-14 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inlet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='received_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='master',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inlet.product'),
        ),
        migrations.AddField(
            model_name='productindex',
            name='received_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productindexitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inlet.product'),
        ),
        migrations.AddField(
            model_name='productindexitem',
            name='product_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inlet.productindex'),
        ),
        migrations.AddField(
            model_name='productindex',
            name='products',
            field=models.ManyToManyField(through='inlet.ProductIndexItem', to='inlet.product'),
        ),
    ]
