# Generated by Django 5.0 on 2023-12-20 01:33

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0003_master_short_uuid_alter_productindexitem_short_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productindexitem',
            name='short_uuid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True),
        ),
    ]
