# Generated by Django 5.0 on 2024-01-07 14:34

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0012_alter_productindexitem_short_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='units_status',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productindexitem',
            name='short_uuid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True),
        ),
    ]
