# Generated by Django 5.0 on 2024-01-08 03:25

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0014_alter_productindexitem_short_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='machine',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productindexitem',
            name='short_uuid',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True),
        ),
        migrations.AddField(
            model_name='master',
            name='Units',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inlet.units'),
            preserve_default=False,
        ),
    ]
