# Generated by Django 5.0 on 2024-01-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0016_remove_master_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productindexitem',
            name='short_uuid',
        ),
    ]
