# Generated by Django 5.0 on 2024-01-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0017_remove_productindexitem_short_uuid'),
        ('units', '0002_remove_unit_id_alter_unit_name_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='units',
        ),
        migrations.RenameField(
            model_name='master',
            old_name='units_status',
            new_name='unit_status',
        ),
        migrations.AddField(
            model_name='master',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='units.unit'),
        ),
        migrations.DeleteModel(
            name='Units',
        ),
    ]
