# Generated by Django 5.0 on 2024-01-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0018_remove_master_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_progress_masters_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
