# Generated by Django 5.0 on 2024-01-12 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0020_remove_master_short_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='requisition',
            field=models.CharField(default=None, max_length=10, null=True,blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='master',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('in_progress', 'In Progress'), ('dead', 'Dead'), ('on_machine', 'on_machine')], default='in_progress', max_length=20),
        ),
    ]
