# Generated by Django 5.0 on 2024-01-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0021_master_requisition_alter_master_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='requisition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
