# Generated by Django 5.0 on 2024-01-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0022_alter_master_requisition'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='machine_added_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
