# Generated by Django 5.0 on 2024-01-22 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0023_master_machine_added_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='machine_added_date',
        ),
    ]
