# Generated by Django 5.0 on 2024-01-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0025_master_machine_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='break_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='deactive_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
