# Generated by Django 5.0 on 2024-01-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0027_productindex_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='resharp_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='master',
            name='resharped',
            field=models.BooleanField(default=False),
        ),
    ]
