# Generated by Django 5.0 on 2024-02-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0030_remove_product_quantity_per_box_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productindex',
            name='is_insert',
        ),
        migrations.RemoveField(
            model_name='productindex',
            name='quantity_per_box',
        ),
        migrations.AddField(
            model_name='master',
            name='is_insert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='master',
            name='quantity_per_box',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
