# Generated by Django 5.0 on 2024-02-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0031_remove_productindex_is_insert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='machine_remove_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
