# Generated by Django 5.0 on 2024-02-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0032_master_machine_remove_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('in_progress', 'In Progress'), ('dead', 'Dead'), ('on_machine', 'on_machine'), ('removed_from_machine', 'removed_from_machine')], default='in_progress', max_length=20),
        ),
    ]
