# Generated by Django 5.0 on 2024-02-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0033_alter_master_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindex',
            name='is_printed',
            field=models.BooleanField(default=False),
        ),
    ]
