# Generated by Django 5.0 on 2024-02-05 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0034_productindex_is_printed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productindex',
            name='is_printed_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_product_indexes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productindex',
            name='received_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_product_indexes', to=settings.AUTH_USER_MODEL),
        ),
    ]
