# Generated by Django 5.0 on 2024-02-06 02:17

import django.core.validators
import inlet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0037_remove_product_uploaded_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productindex',
            name='uploaded_file',
        ),
        migrations.AddField(
            model_name='productindexitem',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='product_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'csv', 'xls', 'xlsx']), inlet.models.ContentTypeValidator(allowed_types=['image/jpeg', 'image/png', 'image/gif', 'application/pdf', 'text/csv', 'application/vnd.ms-excel'])]),
        ),
    ]
