# Generated by Django 5.0 on 2024-02-07 00:05

import django.core.validators
import inlet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0038_remove_productindex_uploaded_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productindexitem',
            old_name='uploaded_file',
            new_name='balanceing_report',
        ),
        migrations.AddField(
            model_name='productindexitem',
            name='drawing',
            field=models.FileField(blank=True, null=True, upload_to='product_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'csv', 'xls', 'xlsx']), inlet.models.ContentTypeValidator(allowed_types=['image/jpeg', 'image/png', 'image/gif', 'application/pdf', 'text/csv', 'application/vnd.ms-excel'])]),
        ),
        migrations.AddField(
            model_name='productindexitem',
            name='inspection_report',
            field=models.FileField(blank=True, null=True, upload_to='product_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'csv', 'xls', 'xlsx']), inlet.models.ContentTypeValidator(allowed_types=['image/jpeg', 'image/png', 'image/gif', 'application/pdf', 'text/csv', 'application/vnd.ms-excel'])]),
        ),
    ]
