# Generated by Django 5.0 on 2024-02-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0039_rename_uploaded_file_productindexitem_balanceing_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplier_gstin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='productindex',
            name='supplier_gstin',
            field=models.CharField(default='Arihant Industries India - 26AAEFA4361Q1Z5', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productindex',
            name='supplier_name',
            field=models.CharField(default=34892453892345789, max_length=100),
            preserve_default=False,
        ),
    ]
