# Generated by Django 5.0 on 2024-02-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0040_remove_product_supplier_gstin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productindex',
            name='supplier_gstin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productindex',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
