# Generated by Django 5.0 on 2024-02-07 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0041_alter_productindex_supplier_gstin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productindexitem',
            old_name='balanceing_report',
            new_name='balancing_report',
        ),
        migrations.RenameField(
            model_name='productindexitem',
            old_name='drawing',
            new_name='drwaing',
        ),
    ]
