# Generated by Django 5.0 on 2024-02-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0042_rename_balanceing_report_productindexitem_balancing_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_unique_reports',
            field=models.BooleanField(default=False),
        ),
    ]
