# Generated by Django 5.0 on 2024-02-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0044_master_balancing_report_master_drwaing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='MaterialCode',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='productindex',
            name='party_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productindex',
            name='party_challan_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
