# Generated by Django 5.0 on 2024-02-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0045_product_materialcode_productindex_party_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindex',
            name='grn_no',
            field=models.CharField(default=102232440411020176, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productindex',
            name='gate_inward_No',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
