# Generated by Django 5.0 on 2024-02-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0046_productindex_grn_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='box_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
