# Generated by Django 5.0 on 2024-02-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0047_master_box_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='static_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
