# Generated by Django 5.0 on 2024-02-16 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0048_master_static_quantity'),
        ('units', '0023_requisitionproduct_total_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='machine',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='units.unit'),
        ),
    ]
