# Generated by Django 5.0 on 2024-02-17 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0049_alter_master_machine_alter_master_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productindex',
            name='grn_no',
        ),
        migrations.RemoveField(
            model_name='productindex',
            name='part_date',
        ),
        migrations.AddField(
            model_name='productindex',
            name='party_chalan_date',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='productindex',
            name='po_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productindex',
            name='gate_inward_No',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
