# Generated by Django 5.0 on 2024-02-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0050_remove_productindex_grn_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='drwaing',
            new_name='drawing',
        ),
    ]
