# Generated by Django 5.0 on 2024-02-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0051_rename_drwaing_master_drawing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productindex',
            name='UOM',
        ),
        migrations.AddField(
            model_name='product',
            name='UOM',
            field=models.CharField(default='SOP', max_length=10),
            preserve_default=False,
        ),
    ]
