# Generated by Django 5.0 on 2024-02-24 05:59

import inlet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0052_remove_productindex_uom_product_uom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productindex',
            name='party_chalan_date',
        ),
        migrations.RemoveField(
            model_name='productindex',
            name='po_date',
        ),
        migrations.AddField(
            model_name='productindex',
            name='grn_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productindex',
            name='part_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productindexitem',
            name='UOM',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='master',
            name='uuid',
            field=models.CharField(default=inlet.models.generate_short_uuid, editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='productindex',
            name='gate_inward_No',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
