# Generated by Django 5.0 on 2024-02-27 05:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0054_remove_product_uom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productindex',
            old_name='part_date',
            new_name='party_challan_date',
        ),
        migrations.AddField(
            model_name='productindex',
            name='SubGlAcNo',
            field=models.PositiveIntegerField(default=111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productindex',
            name='grn_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productindex',
            name='po_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
