# Generated by Django 5.0 on 2024-03-01 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0055_rename_part_date_productindex_party_challan_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productindex',
            name='ammount',
        ),
        migrations.RemoveField(
            model_name='productindex',
            name='rate',
        ),
    ]
