# Generated by Django 5.0 on 2024-03-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0058_alter_productindexitem_short_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productindexitem',
            name='short_quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
