# Generated by Django 5.0 on 2024-03-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0059_alter_productindexitem_short_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindexitem',
            name='unactive_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
