# Generated by Django 5.0 on 2024-03-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0062_productindexitem_actual_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productindex',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('complete', 'Complete'), ('verified', 'verified'), ('active', 'Active'), ('deactive', 'Deactive'), ('in_progress', 'In Progress'), ('dead', 'Dead')], default='unverified', max_length=20),
        ),
    ]
