# Generated by Django 5.0 on 2024-03-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0063_alter_productindex_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productindex',
            name='party_challan_date',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
