# Generated by Django 5.0 on 2024-03-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0064_alter_productindex_party_challan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productindex',
            name='part_bill_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productindex',
            name='grn_no',
            field=models.CharField(max_length=50),
        ),
    ]
