# Generated by Django 5.0 on 2024-03-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0065_alter_productindex_grn_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productindex',
            name='SubGlAcNo',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productindex',
            name='grn_no',
            field=models.CharField(max_length=50, serialize=False),
        ),
        migrations.AlterField(
            model_name='productindex',
            name='part_bill_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productindex',
            name='party_challan_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
