# Generated by Django 5.0 on 2024-03-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0066_alter_productindex_subglacno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productindex',
            name='grn_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='productindex',
            name='grn_no',
            field=models.CharField(max_length=50),
        ),
    ]
