# Generated by Django 5.0 on 2024-03-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0067_productindex_id_alter_productindex_grn_date_and_more'),
    ]

    operations = [        migrations.AlterField(
            model_name='productindex',
            name='grn_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
