# Generated by Django 5.0 on 2024-03-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0068_productindex_id_alter_productindex_grn_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productindex',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=True,
        ),
    ]
