# Generated by Django 5.0 on 2024-03-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0069_productindex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productindex',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
