# Generated by Django 5.0 on 2024-03-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0070_alter_productindex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productindex',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('Allocated', 'allocated'), ('complete', 'Complete'), ('verified', 'verified'), ('active', 'Active'), ('deactive', 'Deactive'), ('in_progress', 'In Progress'), ('dead', 'Dead')], default='unverified', max_length=20),
        ),
    ]
