# Generated by Django 5.0 on 2024-03-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0071_alter_productindex_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive'), ('in_progress', 'In Progress'), ('Allocated', 'allocated'), ('dead', 'Dead'), ('on_machine', 'on_machine'), ('removed_from_machine', 'removed_from_machine')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='productindex',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('complete', 'Complete'), ('verified', 'verified'), ('active', 'Active'), ('deactive', 'Deactive'), ('in_progress', 'In Progress'), ('dead', 'Dead')], default='unverified', max_length=20),
        ),
    ]
