# Generated by Django 5.0 on 2024-03-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0072_alter_master_status_alter_productindex_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
