# Generated by Django 5.0 on 2024-03-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0073_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindex',
            name='compny_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
