# Generated by Django 5.0 on 2024-03-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0074_productindex_compny_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productindex',
            name='complete_activated',
            field=models.DateTimeField(default=None,null=True),
        ),
    ]
