# Generated by Django 5.0.3 on 2024-04-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0075_productindex_complete_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
