# Generated by Django 5.0.3 on 2024-05-05 04:38

import django.core.validators
import inlet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0076_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='balancing_report',
            field=models.FileField(blank=True, null=True, upload_to='~/Reports', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'csv', 'xls', 'xlsx']), inlet.models.ContentTypeValidator(allowed_types=['image/jpeg', 'image/png', 'image/gif', 'application/pdf', 'text/csv', 'application/vnd.ms-excel'])]),
        ),
        migrations.AlterField(
            model_name='master',
            name='drawing',
            field=models.FileField(blank=True, null=True, upload_to='~/Reports', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'csv', 'xls', 'xlsx']), inlet.models.ContentTypeValidator(allowed_types=['image/jpeg', 'image/png', 'image/gif', 'application/pdf', 'text/csv', 'application/vnd.ms-excel'])]),
        ),
        migrations.AlterField(
            model_name='master',
            name='inspection_report',
            field=models.FileField(blank=True, null=True, upload_to='~/Reports', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'csv', 'xls', 'xlsx']), inlet.models.ContentTypeValidator(allowed_types=['image/jpeg', 'image/png', 'image/gif', 'application/pdf', 'text/csv', 'application/vnd.ms-excel'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='MaterialCode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
