# Generated by Django 5.0.3 on 2024-05-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0077_alter_master_balancing_report_alter_master_drawing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='MaterialCode',
            field=models.PositiveIntegerField(default=1234),
            preserve_default=False,
        ),
    ]
