# Generated by Django 4.2.9 on 2024-09-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0078_alter_product_materialcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='TOOLING', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_UOM',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='total_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productindexitem',
            name='recived_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='productindexitem',
            name='requested_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='MaterialCode',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
