# Generated by Django 4.2.9 on 2024-08-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0078_alter_product_materialcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productindexitem',
            name='actual_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='productindexitem',
            name='quantity_received',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productindexitem',
            name='quantity_requested',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productindexitem',
            name='short_quantity',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
