# Generated by Django 4.2.9 on 2024-08-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0079_alter_productindexitem_actual_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='Material_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
