# Generated by Django 4.2.9 on 2024-09-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0079_master_weight_product_category_product_material_uom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='initial_weight',
            field=models.BooleanField(default=False),
        ),
    ]
