# Generated by Django 4.2.9 on 2024-08-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0080_master_material_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('INSERTS', 'Inserts'), ('TOOLING', 'Tooling'), ('MATERIAL', 'Material'), ('NON-TOOLING', 'Non-Tooling'), ('OTHER', 'Other')], default='TOOLING', max_length=20),
        ),
    ]
