# Generated by Django 5.0 on 2023-12-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
    ]
