# Generated by Django 5.0 on 2023-12-20 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0003_alter_saleorder_group_id_alter_saleorder_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outlet.saleordergroup'),
        ),
    ]
