# Generated by Django 5.0 on 2023-12-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0004_alter_saleorder_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
