# Generated by Django 5.0 on 2023-12-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0005_alter_saleorder_vehicle_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleordergroup',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
