# Generated by Django 5.0 on 2024-01-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0006_saleordergroup_vehicle_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleordergroup',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('dispatched', 'dispatched'), ('recived', 'recived')], default='pending', max_length=20),
        ),
    ]
