# Generated by Django 5.0 on 2024-01-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0007_saleordergroup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='driver_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='saleordergroup',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='saleordergroup',
            name='driver_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='saleordergroup',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('dispatched', 'dispatched'), ('recived', 'recived')], default='created', max_length=20),
        ),
    ]
