# Generated by Django 5.0 on 2024-01-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0008_saleorder_destination_saleorder_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('out', 'Out'), ('queue_for_out', 'queue_for_out'), ('recived', 'recived')], default='pending', max_length=20),
        ),
    ]
