# Generated by Django 5.0 on 2024-02-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0009_alter_saleorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderproduct',
            name='added_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
