# Generated by Django 5.0 on 2024-02-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0010_saleorderproduct_added_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
