# Generated by Django 5.0 on 2024-02-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0011_saleorder_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('out', 'Out'), ('queue_for_out', 'queue_for_out'), ('verified_at_gate', 'Verified_at_gate'), ('recived', 'recived')], default='pending', max_length=20),
        ),
    ]
