# Generated by Django 5.0 on 2024-02-09 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0011_saleorder_checked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='checked_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_sale_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='verified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sale_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('out', 'Out'), ('queue_for_out', 'queue_for_out'), ('verified_at_gate', 'Verified_at_gate'), ('recived', 'recived')], default='pending', max_length=20),
        ),
    ]
