# Generated by Django 5.0 on 2024-02-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0012_saleorder_unit_alter_saleorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderproduct',
            name='verified_uuids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
