# Generated by Django 5.0 on 2024-02-12 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0013_saleorderproduct_verified_uuids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderproduct',
            name='checked_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_sale_order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='saleorderproduct',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleorderproduct',
            name='verified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_sale_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleordergroup',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('dispatched', 'dispatched'), ('checked', 'checked'), ('enterd_in_unit', 'enterd_in_unit'), ('recived', 'recived')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='saleorderproduct',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('verified', 'verified')], default='pending', max_length=20),
        ),
    ]
