# Generated by Django 5.0 on 2024-02-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0013_saleorder_unit_alter_saleorder_status_and_more'),
        ('outlet', '0014_saleorderproduct_checked_by_and_more'),
    ]

    operations = [
    ]
