# Generated by Django 5.0 on 2024-02-13 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0015_merge_20240213_0520'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderproduct',
            name='holding_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saleordergroup',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('dispatched', 'dispatched'), ('checked', 'checked'), ('enterd_in_unit', 'enterd_in_unit'), ('recived', 'recived')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='saleorderproduct',
            name='checked_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_order_product_checked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleorderproduct',
            name='verified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_order_product_verified', to=settings.AUTH_USER_MODEL),
        ),
    ]
