# Generated by Django 5.0 on 2024-02-25 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0006_vehicle_status'),
        ('outlet', '0016_saleorderproduct_holding_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleordergroup',
            name='vehicle_no',
        ),
        migrations.AddField(
            model_name='saleordergroup',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managment.vehicle'),
        ),
    ]
