# Generated by Django 5.0.2 on 2024-02-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0017_remove_saleordergroup_vehicle_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='order_date',
            field=models.CharField(default='NONE', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleorder',
            name='order_no',
            field=models.CharField(default='NONE', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleorder',
            name='party_po_date',
            field=models.CharField(default='NONE', max_length=50),
            preserve_default=False,
        ),
    ]
