# Generated by Django 5.0.2 on 2024-02-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0018_saleorder_order_date_saleorder_order_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='grn_number',
        ),
    ]
