# Generated by Django 5.0 on 2024-03-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0020_saleordergroup_master_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleorderproduct',
            old_name='added_count',
            new_name='remaining_quantity',
        ),
    ]
