# Generated by Django 5.0 on 2024-03-04 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0021_rename_added_count_saleorderproduct_remaining_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='bill_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('66fc419b-7c71-4955-98c7-c5263b7022ca'), editable=False, serialize=False, unique=True),
        ),
    ]
