# Generated by Django 5.0 on 2024-03-04 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0022_saleorder_bill_no_saleorder_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('18edecaf-8c85-498c-ac2a-1db78c52ec35'), editable=False, unique=True),
        ),
    ]
