# Generated by Django 5.0 on 2024-03-05 05:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0023_saleorder_id_alter_saleorder_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9b18e396-1d5f-45fe-83d0-f2892cd35b57'), editable=False, unique=True),
        ),
    ]
