# Generated by Django 5.0 on 2024-03-05 05:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0024_saleorder_id_alter_saleorder_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fc9e1484-d188-480b-9145-a50374cf7b41'), editable=False, unique=True),
        ),
    ]
