# Generated by Django 5.0 on 2024-03-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0027_saleorder_id_alter_saleorder_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleorder',
            name='bill_no',
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='order_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
