# Generated by Django 5.0 on 2024-03-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0028_remove_saleorder_bill_no_saleorder_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=True,
        ),

    ]
