# Generated by Django 5.0 on 2024-03-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0029_saleorder_id_alter_saleorder_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleordergroup',
            name='unit',
            field=models.CharField(default='Shri Ram', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='saleorder',
            name='unit',
            field=models.CharField(default='Shri Ram', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleordergroup',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('complete', 'complete'), ('dispatched', 'dispatched'), ('checked', 'checked'), ('enterd_in_unit', 'enterd_in_unit'), ('recived', 'recived')], default='created', max_length=20),
        ),
    ]
