# Generated by Django 5.0 on 2024-03-09 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0014_historicalvehicle_address_and_more'),
        ('outlet', '0030_saleordergroup_unit_alter_saleorder_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleSaleOrderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json', models.JSONField(null=True)),
                ('sale_order_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outlet.saleordergroup')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managment.vehicle')),
            ],
        ),
    ]
