# Generated by Django 5.0 on 2024-03-09 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managment', '0014_historicalvehicle_address_and_more'),
        ('outlet', '0031_vehiclesaleordergroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesaleordergroup',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managment.vehicle'),
        ),
    ]
