# Generated by Django 5.0 on 2024-03-09 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0032_alter_vehiclesaleordergroup_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesaleordergroup',
            name='sale_order_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outlet.saleordergroup'),
        ),
    ]
