# Generated by Django 5.0 on 2024-03-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0033_alter_vehiclesaleordergroup_sale_order_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclesaleordergroup',
            name='sale_order_group',
        ),
        migrations.AddField(
            model_name='vehiclesaleordergroup',
            name='sale_order_groups',
            field=models.ManyToManyField(blank=True, to='outlet.saleordergroup'),
        ),
    ]
