# Generated by Django 5.0 on 2024-03-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0034_remove_vehiclesaleordergroup_sale_order_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesaleordergroup',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
