# Generated by Django 5.0 on 2024-03-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0035_vehiclesaleordergroup_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesaleordergroup',
            name='driver_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
