# Generated by Django 5.0 on 2024-03-16 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0036_vehiclesaleordergroup_driver_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclesaleordergroup',
            name='unit',
        ),
    ]
