# Generated by Django 5.0 on 2024-03-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0038_remove_vehiclesaleordergroup_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclesaleordergroup',
            name='sale_order_groups',
        ),
        migrations.AddField(
            model_name='vehiclesaleordergroup',
            name='sale_order_groups',
            field=models.JSONField(null=True),
        ),
    ]
