# Generated by Django 5.0 on 2024-03-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0039_remove_vehiclesaleordergroup_sale_order_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclesaleordergroup',
            name='sale_order_groups',
        ),
        migrations.AddField(
            model_name='vehiclesaleordergroup',
            name='order_groups',
            field=models.ManyToManyField(blank=True, to='outlet.saleordergroup'),
        ),
    ]
