# Generated by Django 5.0 on 2024-03-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0040_remove_vehiclesaleordergroup_sale_order_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleordergroup',
            name='allocated',
            field=models.BooleanField(default=False),
        ),
    ]
