# Generated by Django 5.0 on 2024-03-18 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0041_saleordergroup_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesaleordergroup',
            name='arrive_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
