# Generated by Django 5.0.3 on 2024-04-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0042_vehiclesaleordergroup_arrive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='uuids',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
