# Generated by Django 5.0.3 on 2024-04-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0043_alter_saleorder_uuids'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclesaleordergroup',
            name='TransporterName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
