# Generated by Django 5.0.3 on 2024-04-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0044_vehiclesaleordergroup_transportername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclesaleordergroup',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
