# Generated by Django 5.0.3 on 2024-04-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0045_alter_vehiclesaleordergroup_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleordergroup',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
