# Generated by Django 5.0.3 on 2024-04-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0046_alter_saleordergroup_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleordergroup',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
