# Generated by Django 5.0.6 on 2024-07-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0047_saleordergroup_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorder',
            name='invoice_no',
            field=models.CharField(blank=True, null=True),
        ),
    ]
