# Generated by Django 5.0.6 on 2024-07-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0048_saleorder_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleordergroup',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
