# Generated by Django 4.2.9 on 2024-09-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlet', '0049_alter_saleordergroup_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleorderproduct',
            name='added_weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='saleorderproduct',
            name='remaning_weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='saleorderproduct',
            name='total_weight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
