# Generated by Django 5.0 on 2024-01-11 05:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_remove_unit_id_alter_unit_name_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_no', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('tool', models.JSONField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=100)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.machine')),
            ],
        ),
    ]
