# Generated by Django 5.0 on 2024-01-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_requisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='tool',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
