# Generated by Django 5.0 on 2024-01-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_alter_requisition_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='active_tools',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
