# Generated by Django 5.0 on 2024-01-11 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0020_remove_master_short_uuid'),
        ('units', '0005_machine_active_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='product',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='inlet.product'),
            preserve_default=False,
        ),
    ]
