# Generated by Django 5.0 on 2024-01-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_requisition_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='tool',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
