# Generated by Django 5.0 on 2024-01-22 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0008_requisition_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='unit',
            field=models.ForeignKey(default='Shri Ram', on_delete=django.db.models.deletion.CASCADE, to='units.unit'),
        ),
    ]
