# Generated by Django 5.0 on 2024-01-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0009_requisition_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='active_tools',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
