# Generated by Django 5.0 on 2024-01-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0010_alter_machine_active_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='is_old_verified',
            field=models.BooleanField(default=False),
        ),
    ]
