# Generated by Django 5.0 on 2024-01-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0011_requisition_is_old_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='break_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requisition',
            name='resharp_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
