# Generated by Django 5.0 on 2024-01-31 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inlet', '0028_master_resharp_count_master_resharped'),
        ('units', '0012_requisition_break_count_requisition_resharp_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='product',
        ),
        migrations.CreateModel(
            name='RequisitionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_quantity', models.PositiveIntegerField(default=0)),
                ('resharp_quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inlet.product')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.requisition')),
            ],
        ),
        migrations.AddField(
            model_name='requisition',
            name='products',
            field=models.ManyToManyField(through='units.RequisitionProduct', to='inlet.product'),
        ),
    ]
