# Generated by Django 5.0 on 2024-01-31 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0013_remove_requisition_product_requisitionproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='break_count',
        ),
        migrations.RemoveField(
            model_name='requisition',
            name='resharp_count',
        ),
    ]
