# Generated by Django 5.0 on 2024-02-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0015_alter_requisition_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionproduct',
            name='break_uuid',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='requisitionproduct',
            name='resharp_uuid',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
