# Generated by Django 5.0 on 2024-02-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0016_requisitionproduct_break_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionproduct',
            name='added_break_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='requisitionproduct',
            name='added_resharp_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
