# Generated by Django 5.0 on 2024-02-14 17:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0017_requisitionproduct_added_break_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnMaster',
            fields=[
                ('uuid', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('return_type', models.CharField(choices=[('break', 'Break'), ('resharp', 'Resharp')], max_length=20)),
                ('machine_name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=100)),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.requisition')),
            ],
        ),
    ]
