# Generated by Django 5.0 on 2024-02-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0018_returnmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnmaster',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
