# Generated by Django 5.0 on 2024-02-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0019_alter_returnmaster_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionproduct',
            name='status',
            field=models.CharField(choices=[('incomplete', 'incomplete'), ('complete', 'complete')], default='incomplete', max_length=20),
        ),
    ]
