# Generated by Django 5.0 on 2024-02-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0020_requisitionproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionproduct',
            name='is_old_verified',
            field=models.BooleanField(default=False),
        ),
    ]
