# Generated by Django 5.0 on 2024-02-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0023_requisitionproduct_total_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionproduct',
            name='allocate_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
